### PR TITLE
Initial port to 8.x

### PR DESCRIPTION
**Pull request by jhedstrom**
By no means is this complete, but 2 of the major tests are now passing (`SubscribersTest` and `QueueTest`). I won't have time to work on this again until next week, so I'm posting this here for review now.

### CODE REVIEW

**Comment by amitaibu** [comment]
Awesome, I'll review this.

**Comment by amitaibu** [comment]
Sorry, In holiday, so didn't get to it yet. If you prefer I can merge, and do a post-merge review. Let me know ;)

**Comment by jhedstrom** [comment]
I'm back now as well, and can continue working on this branch for the time being.

**Comment by jhedstrom** [comment]
@amitaibu this is probably good to go in now. I'm currently working on `message_subscribe_ui`, which warrants a separate PR I think. There will be some additional cleanup work following on this.

**Comment by amitaibu** [comment]
Haven't reviewed yet, but merged so it won't unblock your work. Thanks!

message_subscribe_ui could be pushed to a second step - probably worth doing clean-ups and going back to todos in the API -- if you got time of course ;)

**Pull request merged**
