### PR TITLE
Message subscribe UI and Email submodules

### PR DESCRIPTION
**Pull request by jhedstrom**
This is an initial port of the UI and email sub-modules.

### CODE REVIEW

**Comment by jhedstrom** [comment]
I'm going to roll the email submodule into this one too. I'll update when ready for review.

**Comment by jhedstrom** [comment]
@amitaibu this is pretty good to merge now I think. I have a few more cleanup tasks in mind, but those will make sense in separate issues (I'm going to work on deprecating/removing the hooks and switching to proper events/subscribers, for instance).

**Comment by amitaibu** [comment]
I'll do a post-merge review.

btw, care to get a commit access? ;)

**Comment by jhedstrom** [comment]
> btw, care to get a commit access? ;)

Sure! That would make the fine-tuning a bit quicker :)

**Comment by jhedstrom** [comment]
@amitaibu ^^

**Comment by amitaibu** [comment]
Mazal tov, you got it :)

**Pull request merged**
